from GooglePatentsScraper import scraper

test_cases = [
    ("(TANK) AND ((FREQUENCY OR CYCLE) NEAR/4 (CHANG* OR VARIABLE OR VARY* OR CHANGE OR INCREASE \
    OR DECREASE OR LIGHT OR HEAVY OR FULL OR BIG* OR SMALL*))/ AND ((CHANGE OR VARIABLE OR CHANG* \
    OR INCREASE OR DECREASE OR LIGHT OR HEAVY OR FULL OR BIG* OR SMALL*) 5D (LOAD)) AND \
    ((POWER 4D (CONVERT*)) OR BOOST OR BUCK OR SMPS)", 39),

    # https://patents.google.com/xhr/query?url=q%3D(TANK)%2BAND%2B((FREQUENCY%2BOR%2BCYCLE)%2BNEAR%252f4%2B(CHANG*%2BOR%2BVARIABLE%2BOR%2BVARY*%2BOR%2BCHANGE%2BOR%2BINCREASE%2BOR%2BDECREASE%2BOR%2BLIGHT%2BOR%2BHEAVY%2BOR%2BFULL%2BOR%2BBIG*%2BOR%2BSMALL*))%252f%2BAND%2B((CHANGE%2BOR%2BVARIABLE%2BOR%2BCHANG*%2B%2BOR%2BINCREASE%2BOR%2BDECREASE%2BOR%2BLIGHT%2BOR%2BHEAVY%2BOR%2BFULL%2BOR%2BBIG*%2BOR%2BSMALL*)%2B5D%2B(LOAD))%2BAND%2B((POWER%2B4D%2B(CONVERT*))%2BOR%2BBOOST%2BOR%2BBUCK%2BOR%2BSMPS)%26oq%3D(TANK)%2BAND%2B((FREQUENCY%2BOR%2BCYCLE)%2BNEAR%252f4%2B(CHANG*%2BOR%2BVARIABLE%2BOR%2BVARY*%2BOR%2BCHANGE%2BOR%2BINCREASE%2BOR%2BDECREASE%2BOR%2BLIGHT%2BOR%2BHEAVY%2BOR%2BFULL%2BOR%2BBIG*%2BOR%2BSMALL*))%252f%2BAND%2B((CHANGE%2BOR%2BVARIABLE%2BOR%2BCHANG*%2B%2BOR%2BINCREASE%2BOR%2BDECREASE%2BOR%2BLIGHT%2BOR%2BHEAVY%2BOR%2BFULL%2BOR%2BBIG*%2BOR%2BSMALL*)%2B5D%2B(LOAD))%2BAND%2B((POWER%2B4D%2B(CONVERT*))%2BOR%2BBOOST%2BOR%2BBUCK%2BOR%2BSMPS)&exp=

    ("(TANK NEAR/4 RESONA*) AND ((FREQUENCY OR CYCLE) NEAR/4 (CHANG* OR VARIABLE OR VARY* OR \
    CHANGE OR INCREASE OR DECREASE OR LIGHT OR HEAVY OR FULL OR BIG* OR SMALL*))/ AND \
    ((CHANGE OR VARIABLE OR CHANG* OR INCREASE OR DECREASE OR LIGHT OR HEAVY OR FULL OR BIG* OR SMALL*) \
    5D (LOAD)) AND ((POWER 4D (CONVERT*)) OR BOOST OR BUCK OR SMPS)", 4),

    ("((TANK OR LC OR LLC OR LCL) NEAR/4 RESONA*) AND ((FREQUENCY OR CYCLE) NEAR/4 (CHANG* OR VARIABLE \
    OR VARY* OR CHANGE OR INCREASE OR DECREASE OR LIGHT OR HEAVY OR FULL OR BIG* OR SMALL*))/ AND \
    ((CHANGE OR VARIABLE OR CHANG* OR INCREASE OR DECREASE OR LIGHT OR HEAVY OR FULL OR BIG* OR SMALL*) \
    5D (LOAD))", 196),

    ("((TANK OR LC OR LLC OR LCL) NEAR/4 RESONA*) AND ((FREQUENCY OR CYCLE) NEAR/4 (CHANG* OR VARIABLE \
    OR VARY* OR CHANGE OR INCREASE OR DECREASE OR LIGHT OR HEAVY OR FULL OR BIG* OR SMALL*))/ AND \
    ((CHANGE OR VARIABLE OR CHANG* OR INCREASE OR DECREASE OR LIGHT OR HEAVY OR FULL OR BIG* OR SMALL*) \
    5D (LOAD OR CURRENT OR SINK))", 459),

    ("(LOAD NEAR/3 (VALUE OR MAGNITUDE) NEAR/4 (CHANG* OR VARY OR VARIABLE OR INCREASE OR DECREASE OR CHANG*)) \
    AND (FREQUENCY NEAR/3 (VALUE OR MAGNITUDE) NEAR/4 (CHANG* OR VARY OR VARIABLE OR INCREASE OR \
    DECREASE OR CHANG*))", 135828)
]


if __name__ == "__main__":
    # print(test_cases[0])
    for i, tc in enumerate(test_cases):
        print("Output of test case {} : ".format(i+1))
        print(scraper(test_cases[i][0]))
